### ISSUE TITLE
Change SDL version to 0.32

### ISSUE THREAD

**Issue by TheRadioGuy** [bcamp1/Gravisim#3]

**Comment by bcamp1** [comment]
When I try to change the version to 0.32 in cargo.toml, I get these errors. Anyone know how to fix it?
![screen shot 2019-03-06 at 10 51 38 pm](https://user-images.githubusercontent.com/34494650/53935132-7c6cf980-4062-11e9-8b14-542562df51dd.png)

**Comment by TheRadioGuy** [comment]
What is your rust version?

**Comment by TheRadioGuy** [comment]
![image](https://user-images.githubusercontent.com/23637939/54072036-4b6d0e80-4286-11e9-8049-3cb6cf9ab7ba.png)

**Comment by bcamp1** [comment]
Thanks, with the updated rust version it worked great!
